[workspace]
members = [
    "resource_market",
    "roulette",
    "socialism_dao",
    "tictactoe",
    "simple-dex",
    "psp22",
    "psp22-traits",
]
resolver = "2"
[profile.release]
panic = "unwind"
