name: forge build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # TODO Might have to cd into the evm directory for forge commands to work.

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      # Tests are not expected to work on `main` because it is starter code.
      # - name: Run Forge tests
      #   run: |
      #     forge test -vvv
      #   id: test
